apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-component
  namespace: demo2
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: wat
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: devfile-sample-go-basic-component
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: devfile-sample-go-basic-component-
      labels:
        build.appstudio.openshift.io/application: wat
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: devfile-sample-go-basic-component
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: demo2
    spec:
      params:
      - name: git-url
        value: https://github.com/devfile-samples/devfile-sample-go-basic.git
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:demo2-devfile-sample-go-basic-component2-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:devel
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: devfile-sample-go-basic-component/$(tt.params.git-revision)
    status: {}
status: {}
