apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic
    app.kubernetes.io/part-of: wat
  name: devfile-sample-go-basic-component
  namespace: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-go-basic-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-go-basic-component
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:demo2-devfile-sample-go-basic-component
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
